framework:
    secret: "%env(APP_SECRET)%"
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        enabled: true
        handler_id: session.handler.native_file
        save_path: "%kernel.project_dir%/var/sessions/%kernel.environment%"
        # cookie_httponly: true
        cookie_secure: true
        cookie_samesite: lax
        gc_maxlifetime: 10800

    validation: { enable_annotations: true }

    #esi: true
    #fragments: true
    php_errors:
        log: true

    ide: "%env(resolve:CODE_EDITOR)%"

    http_client:
        default_options:
            verify_peer: true
