# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public/"
                cache_prefix: uploads/optimized

    default_filter_set_settings:
        quality: 100
        jpeg_quality: null
        png_compression_level: null
        png_compression_filter: null
        format: null
        animated: false
        cache: null
        data_loader: null
        default_image: null
        filters: {}
        post_processors: {}

    filter_sets:
        cache: ~
        # the name of the "filter set"
        thumbnail:
            # adjust the image quality to 75%
            quality: 75
            # list of transformations to apply (the "filters")
            filters:
                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [120, 90], mode: outbound }
                # create a 2px black border: center the thumbnail on a black background
                # 4px larger to create a 2px border around the final image
                background:
                    { size: [124, 94], position: center, color: "#000000" }
        scan_high:
            filters:
                portrait_rotation_filter: ~
                sharpen_filter: ~
                scale:
                    dim: [3508, 3508]
                interlace:
                    mode: line
            quality: 75
        scan_medium:
            filters:
                portrait_rotation_filter: ~
                # grayscale_filter: ~
                sharpen_filter: ~
                scale:
                    dim: [2048, 2048]
                interlace:
                    mode: line
                background: { position: center, color: "#000000" }
            quality: 50
        scan_low:
            filters:
                portrait_rotation_filter: ~
                grayscale_filter: ~
                sharpen_filter: ~
                scale:
                    dim: [1024, 1024]
                # rotate:
                #     angle: 90
                # grayscale: ~
            quality: 40
