twig:
    default_path: "%kernel.project_dir%/templates"
    paths:
        "%kernel.project_dir%/assets/css": styles
        "%kernel.project_dir%/assets/images": images
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        [
            "bootstrap_4_layout.html.twig",
            "form/bootstrap_4_horizontal.html.twig",
        ]
    globals:
        APP_ENV: "%app_env%"
        YES: 1
