twig:
    default_path: "%kernel.project_dir%/templates"
    paths:
        "%kernel.project_dir%/assets/css": styles
        "%kernel.project_dir%/public/images": images
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        [
            "bootstrap_5_layout.html.twig",
            "form/bootstrap_5_horizontal.html.twig",
        ]
    globals:
        app_env: "%app_env%"
        YES: 1
